version: "3.5"
services:
  #############################
  #     Parte del backend     #
  #############################
  server:
    container_name: backend-container
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  #############################
  #    Parte del frontend     #
  #############################
  client:
    container_name: frontend-container
    depends_on:
      - server
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
  #############################
  # Parte de la base de datos #
  #############################
  db:
    container_name: database-container
    image: mongo
    restart: always
    ports:
      - "9090:27017"